viewer/dbviewer/urls.py
from django.urls import path

from . import views

app_name = 'dbviewer'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:record_id>/', views.detail, name='detail')
]

viewer/vrf_viewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dbviewer.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/dbviewer/models.py
from django.db import models

# Create your models here.
import inspect


class VRFRecord(models.Model):
    idx = models.BigIntegerField()
    seed = models.CharField(max_length=64)
    input = models.CharField(max_length=200)
    output = models.CharField(max_length=64)
    proof = models.CharField(max_length=162)

    @staticmethod
    def user_input_fields():
        return ["USER NAME", "SLOT NUMBER"]

    def parse_user_input(self):
        ln = len(self.user_input_fields())
        res = self.input.split('|', ln)
        if len(res) < ln + 1:
            res += ["None"] * (ln + 1 - len(res))
        return res

    def get_user_output(self):
        out = int(self.output, 16) % 6 + 1
        return out

    def get_user_output_logic(self):
        source = inspect.getsource(self.get_user_output)
        output = ""
        for line in source.split('\n'):
            # Assuming one tab is 4 spaces
            output += line[4:] + '\n'
        return output[:-1]

    def get_user_input_table(self):
        res = []
        input_fields = self.user_input_fields()
        user_input = self.parse_user_input()

        for i in range(len(input_fields)):
            col = {'type': input_fields[i], 'value': user_input[i]}
            res.append(col)

        if len(user_input) > len(input_fields):
            assert len(user_input) == len(input_fields) + 1
            res.append({'type': 'Extra Input', 'value': user_input[-1]})

        return res

    def get_user_output_table(self):
        res = [{
            'type': 'Output',
            'value': self.get_user_output()
        }, {
            'type': 'Output Logic',
            'value': self.get_user_output_logic()
        }]
        return res

class OutputInfo(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=200)


viewer/dbviewer/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse, Http404
from .models import VRFRecord, OutputInfo


def static(**kwargs):
    def decorate(func):
        for k in kwargs:
            setattr(func, k, kwargs[k])
        return func

    return decorate


@static(last_update=None, loading=False)
def index(request):
    import time, threading
    cur_time = time.time()
    last_update = index.last_update
    if not index.loading and (last_update is None
                              or cur_time - last_update > 10):
        print("Last update: {}".format(last_update))
        print("Current time: {}".format(cur_time))

        index.loading = True
        t = threading.Thread(target=refresh, args=())
        t.start()
        index.last_update = cur_time

    latest_record_list = VRFRecord.objects.order_by('-id')

    if latest_record_list is None:
        return render(request, 'dbviewer/index.html', {'table_header': None})

    table_header = VRFRecord.user_input_fields()
    table_header.append("Output Value")
    table_header.append("Output Name")

    table_rows = []
    for record in latest_record_list:
        row = record.parse_user_input()[:-1]
        user_output = record.get_user_output()

        row.append(user_output)
        
        try:
            output_info = OutputInfo.objects.get(pk=user_output)
            row.append(output_info.name)
        except OutputInfo.DoesNotExist:
            row.append("None")
        
        table_rows.append({'id': record.id, 'idx': record.idx, 'values': row})

    context = {'table_header': table_header, 'table_rows': table_rows}
    return render(request, 'dbviewer/index.html', context)


def detail(request, record_id):
    record = get_object_or_404(VRFRecord, pk=record_id)
    user_input_table = record.get_user_input_table()
    user_output_table = record.get_user_output_table()

    user_output = record.get_user_output()

    output_info = get_object_or_404(OutputInfo, pk=user_output)
    user_output_table.extend([{
        'type': 'Output Name',
        'value': output_info.name
    }, {
        'type': 'Output Image',
        'image': output_info.image,
    }])


    context = {
        'record': record,
        'uinput': user_input_table,
        'uoutput': user_output_table
    }

    return render(request, 'dbviewer/detail.html', context)


def refresh():
    import requests
    try:
        r = requests.get('http://rb-tree.xyz/citeivapi/size')
        size_api = r.json()['index']
        size_db = VRFRecord.objects.count()

        for i in range(size_db, size_api):
            r = requests.get(
                'http://rb-tree.xyz/citeivapi/get/{}'.format(i + 1))
            data = r.json()

            record = VRFRecord(
                idx=i + 1,
                seed=data['seed'],
                input=data['input'],
                output=data['output'],
                proof=data['proof'])
            record.save()
        print("Refresh successful: {} to {}".format(size_db, size_api))
    except Exception as e:
        print("Failed to handle: {}".format(e))
    index.loading = False

viewer/dbviewer/templates/dbviewer/detail.html
{% extends 'dbviewer/template.html' %} 
{% block 'body' %}
<div>
    <h1>VRF Data</h1>
</div>
<div class="info">
    <h2>Raw Information</h2>
    <table class="info-table">
        <tbody>
            <tr>
                <th class="info-col1">Index</th>
                <th class="info-col2"> {{ record.idx }}</th>
            </tr>
            <tr>
                <th class="info-col1">Seed</th>
                <th class="info-col2"> {{ record.seed }}</th>
            </tr>
            <tr>
                <th class="info-col1">Input</th>
                <th class="info-col2"> {{ record.input }}</th>
            </tr>
            <tr>
                <th class="info-col1">Output</th>
                <th class="info-col2"> {{ record.output }}</th>
            </tr>
            <tr>
                <th class="info-col1">Proof</th>
                <th class="info-col2"> {{ record.proof }}</th>
            </tr>
        </tbody>
    </table>
    <h2>User Information</h2>
    <h3>User Input</h3>
    <table class="info-table">
        <tbody>
            {% for column in uinput %}
            <tr>
                <th class="info-col1">{{ column.type }}</th>
                <th class="info-col2">{{ column.value }}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h3>User Output</h3>
    <table class="info-table">
        <tbody>
            {% for column in uoutput %}
            <tr>
                <th class="info-col1">{{ column.type }}</th>
                {% if column.image %}
                <th class="info-col2"><img src="{{ column.image.url }}"></th>
                {% else %}
                <th class="info-col2">{{ column.value }}</th>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

viewer/dbviewer/templates/dbviewer/index.html
{% extends 'dbviewer/template.html' %} 
{% block 'body' %}
{% if table_header %}
<div>
    <h1>Latest VRF Records</h1>
</div>
<table class="table">
    <thead>
        <tr>
            <th style="width: 5%;">Link</th>
            <th style="width: 5%;">Index</th>
            {% for value in table_header %}
                <th>{{ value }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in table_rows %}
        <tr>
            <th class="text-center"><a href="{% url 'dbviewer:detail' row.id %}">Go</a></th>
            <th class="text-center">{{ row.idx }}</th>
            {% for value in row.values %}
            <th>{{ value }}</th>
            {% endfor %}
        </tr> 
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No data!</p>
{% endif %}
{% endblock %}

viewer/dbviewer/templates/dbviewer/template.html
{% load static %}

<head>
<title>VRF Viewer</title>
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="{% static 'dbviewer/style.css' %}">
</head>

<body>
<div class="header">
    <p>VRF Viewer</p>
    <a href="/">Index Table</a>
</div>
<div class="content">
{% block 'body' %}
{% endblock %}
</div>
<div class="footer">

</div>
</body>